__include__: [
  '../dataset/bdd_detection_kaggle.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: /kaggle/working/output/rtdetrv2_hgnetv2_l_6x_coco

epoches: 3

RTDETR:
  backbone: HGNetv2


HGNetv2:
  name: 'M'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  pretrained: True
  use_lab: True

HybridEncoder:
  in_channels: [384, 768, 1536]
  hidden_dim: 256
#  depth_mult: 0.67
  dysample: True
  bifpn: True

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001

